version: '3'
services:
  raspi-pico-build:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - LOCAL_UID=${LOCAL_UID}
      - LOCAL_GID=${LOCAL_GID}
      - LOCAL_USER=${LOCAL_USER}
      - LOCAL_GROUP=${LOCAL_GROUP}
    container_name: ${CONTAINER}
    tty: true
    stdin_open: true
    command:
      - "/bin/bash"
